source = ["polynomial-interpolation.tex"]
sequence = ["lualatex", "upbibtex"]

[programs.lualatex]
command = "lualatex"
opts = ["-interaction=nonstopmode", "-file-line-error"]
aux_file = "%B.aux"
aux_empty_size = 9

[programs.upbibtex]
command = "upbibtex"
target = "%B.bib"
args = ["%B"]
postprocess = "lualatex"
